name: Build LaTeX document
on: [push]
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Literature/main.tex
      - name: Check if PDF was generated
        run: |
          if [ ! -f main.pdf ]; then
            echo "PDF was not generated."
            exit 1
          fi
      - name: Commit PDF
        id: commit_pdf
        run: |
          if [ -f main.pdf ]; then
            git config --local user.email "action[bot]@github.com"
            git config --local user.name "github-actions[bot]"
            git add main.pdf
            git commit -m "[bot] updated PDF file" || echo "No changes to commit"
          else
            echo "No PDF file found, skipping commit."
          fi
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: +1
          format: 'DD-MM-YYYY-HH-mm-ss'
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: main compiled on ${{ steps.time.outputs.time }}
          tag_name: ${{ steps.time.outputs.time }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./main.pdf
          asset_name: main-${{ steps.time.outputs.time }}.pdf
          asset_content_type: application/pdf
      - name: Push changes
        if: steps.commit_pdf.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
